INSERT INTO description (id, content) VALUES (12759, "refrigerador eletrolux duplex fost free, exceto linha prata, com capacidade entre 352 e 480 l.");
INSERT INTO description (id, content) VALUES (7587, "jogo de lençol, solteiro, tecido fio misto (2 lençóis e 1 fronha)");
INSERT INTO description (id, content) VALUES (1425, "azeitona verde sem caroço vale fértil, vidro , peso liquido 335g, peso drenado 160g");
INSERT INTO description (id, content) VALUES (4479, "chocolate em barra diamante negro, lacta. embalagem com 90 g.");
INSERT INTO description (id, content) VALUES (2829, "caneta hidrográfica pacote com 12 cores");
INSERT INTO description (id, content) VALUES (558, "aparelho de telefone com fio intelbrás tc20");
INSERT INTO description (id, content) VALUES (1538, "açúcar refinado alto alegre. pacote com 1k.");
INSERT INTO description (id, content) VALUES (1747, "bermuda feminina infantil jeans ou brim, tamanho de 1 a 3 anos");
INSERT INTO description (id, content) VALUES (13494, "sapato social masculino de couro");
INSERT INTO description (id, content) VALUES (4256, "calça comprida masculina infantil de qualquer tecido (exceto jeans ou brim), tamanho de 1 a 3 anos");
INSERT INTO description (id, content) VALUES (1092, "alvejante urca sem cloro embalagem 1,5l");
INSERT INTO description (id, content) VALUES (9038, "macarrão fortaleza ninho c/ ovos - 500 g");
INSERT INTO description (id, content) VALUES (3208, "charque traseiro - embalagem a vácuo de 1 kg - qualquer marca");
INSERT INTO description (id, content) VALUES (7743, "kit com 3 calcinhas tipo biquíni ou tanga de microfibra ou poliamida e elastano");
INSERT INTO description (id, content) VALUES (3373, "coca cola garrafa descartável  600 ml.");
INSERT INTO description (id, content) VALUES (7829, "lasanha sadia q.q. sabor. caixa com 600 g.");
INSERT INTO description (id, content) VALUES (9651, "mesa quadrada p/ copa ou cozinha, c/ 4 cadeiras, em qq padrão.");
INSERT INTO description (id, content) VALUES (15237, "team up 4, studant book (with work book), 9º ano, ed. ftd, f. kavanagh, c. l. moore, c. e. morris, e. canaleti, m. huber, a. smith, j. cattunar, paola tite, ana capeta fiorini, cris gontow isbn	7898592131461");
INSERT INTO description (id, content) VALUES (16306, "ventilador de mesa arno 40cm 6 pás 3 velocidades.");
INSERT INTO description (id, content) VALUES (3642, "conjunto masculino infantil de camiseta t-shirt de manga curta/bermuda, tamanho de 4 a 10 anos");
INSERT INTO description (id, content) VALUES (4248, "calça comprida feminina de qualquer tecido (exceto jeans ou brim), com detalhes (bordado, strass ou outro)");
INSERT INTO description (id, content) VALUES (4683, "conjunto masculino infantil de camiseta t-shirt/bermuda, tamanho de 4 a 10 anos");
INSERT INTO description (id, content) VALUES (8700, "leite fermentado com polpa de frutas integral paulista festival de frutas bandeja com 6 unidades, 540g");
INSERT INTO description (id, content) VALUES (10906, "papel higienico, neve toque de seda,  neutro, rolo c/ 30m, folha dupla - 16 unidades");
INSERT INTO description (id, content) VALUES (1006, "absorvente interno ob, 8 unidades");
INSERT INTO description (id, content) VALUES (13856, "short masculino de qualquer tecido (exceto jeans ou brim)");
INSERT INTO description (id, content) VALUES (10091, "massa para pastel  - pastelatt (fresca) - 500g");
INSERT INTO description (id, content) VALUES (16330, "vestido longo, de qualquer tecido (incluindo jeans ou brim), com detalhes (bordado, renda ou outro)");
INSERT INTO description (id, content) VALUES (14177, "sandália de material sintético com salto fino");
INSERT INTO description (id, content) VALUES (13295, "saia jeans ou brim (exceto longa), sem detalhes");
INSERT INTO description (id, content) VALUES (3797, "cortina voil c/ forro corta luz 2,00x1,80 / 2,60x1,80m / 2,80x1,80m  / 2,60x1,70m com ilhos p/ varão");
INSERT INTO description (id, content) VALUES (9386, "maçã vermelha importada - kg");
INSERT INTO description (id, content) VALUES (7678, "jogo puzzle com 100 peças");
INSERT INTO description (id, content) VALUES (4894, "delineador líquido para olhos intense preto - boticario");
INSERT INTO description (id, content) VALUES (2712, "cama de casal revestida em qq padrao");
INSERT INTO description (id, content) VALUES (9082, "maionese  hellmanns  sem limão, pote plástico peso líquido 500 g/ 500 ml");
INSERT INTO description (id, content) VALUES (7507, "introdução ao estudo do direito – 41.ª ed. (2019) – paulo nader -isbn: 9788530982539");
INSERT INTO description (id, content) VALUES (11651, "presunto sadia cozido, a granel fatiado, kg");
INSERT INTO description (id, content) VALUES (13129, "risperidona 2mg, caixa com 30 comprimidos (medicamento genérico) - sandoz");
INSERT INTO description (id, content) VALUES (15641, "uva niágara - kg");
INSERT INTO description (id, content) VALUES (14989, "tinta suvinil toque de seda acrílico premium acetinado lata 18l");
INSERT INTO description (id, content) VALUES (9253, "margarina cremosa qualy com sal pote 250 g");
INSERT INTO description (id, content) VALUES (8018, "leite compleite, tipo c, saco plástico - litro");
