INSERT INTO `product_item` (`name`,
                           `place_name`,
                           `price`,
                           `place_url`,
                           `product_url`,
                           `query`,
                           `original_query`,
                           `product_img_url`,
                           `last_updated`,
                           `metadata`)
VALUES ('Arroz Branco Longo-fino Tipo 1 Camil 5 Kg',
        'Carrefour',
        'R$ 25,00',
        'https://mercado.carrefour.com.br/',
        'https://mercado.carrefour.com.br/arroz-branco-longo-fino-tipo-1-camil-todo-dia-5kg-115789',
        'arroz integral 5kg',
        'arroz integral tipo 1 5kg',
        'https://carrefourbr.vtexassets.com/arquivos/ids/193474-1600-auto?width=1600&height=auto&aspect=true',
        '18/02/2021',
        'Grupo Camil, Pacote, Arroz, Branco, Polido, Long-fino');
